language: node_js
node_js:
- '16.18.1'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  - secure: KzX3tGD+y6Yx72u0+QpC4nnFnYbFDLvMmq+1Z5qD6CvW+yqDfd9k+iAWppcdUfXJQoSgymihx2u7bj8K4pEx74sKkbPlDEog0WpUB0oazuLEzlGrRr/LGjoY0jzRvoi7s4Ly/inPgM3oA4egKneGHo+q8/Cg4yBoTTNcNZHl2qZ8zV/XvLLjfJlRzdBWfqS8aYwIehJCFGpfyW0yF1uFFn9WnO9BnqID7xT24Vk8WYH/FEYMnB1fxDynaAoUGS6A67Kw/mHTT0pQFkkUxRuv/AsQa+YRozuDcw1ixguHy0TRiVt6h/zp9oQNaZfZykQKWv2xJYwnzh0DuowW3w8fghf0ZehNUqMopsagpkTfPxZibBnSBOfhX3dScaV+QP5UDsYGCV8cL6eGjtvJll5Q8Nh5hX4d5u7nav8Qhjv4aLHe12DYe6OuZeF3ROhUslQ2MKKIrTlSCO+amVuaYLVr0szXQiBp++4gHmvCQzo8SUkT1fP7/yIutWhacoQuHIokG1mEnHZB0ZkU81WngItaA+5wUgNzvsa0Ro8AvEGP85s4y5WmC4LeL2PRwmgjwHVoWZYy5pSFy76q3MyBMeyTGHMAEbXqs2XyO0R0IbgPbNJHzJz67aBUmeaNS++6d9MgeZs2D/8L3OG0Ygh6g8P3Q9kvAsDhcYBkCPTjkdPu2ng=
  - secure: Upbz+NTewg6DX9ld+Ga7IBat3o2/bHuLrqfcLi+1qA1XXNOZy3a/sfhuLJZ1HCZ6HXS6cl+A5mKGhfr/fN2x7rT2z6+y26yf/X/f6qSY9oYutto0iPmV6UvyiW/zpzgDkcAA+bDehX612bevHckuPMvMyXAI76YgHv0l/jt5fkkX2UlLxyUOKuElLwAgFBItmlwZ00xuJKSb34jtVmSZ1/9XQOnVEsfhIyt909QtBzZEkmx5lZHHmdwcbOSmzK9sJu7IgWd0tWFV4wmWAe7vnP8eTEw3wFKcIzlliCfmNvHJjxiiHoQsaCaO/GH5NM6f7kXdEMvE5J/Wok3UCe9OPuJ/vVmtzshzoklIr/b2Qtz1gwT7f7sLp1ureAteFLv+b1vWfX6IG30F4hsJgIVe7ln6Hz7aRDRwt368oJfh6020zJS2EQdUEWSbt9m/FybffMd9lFFC/gOt/D9ZRs7ZTDOL+9bp50cQ3NqpXTiC9oUCaDv5m3fJ8RpSNwpznrldY/kuVrPVsAIB73dRXE5bhvWX/BKB/NAmcRi1b/xEEJ4XgXWbNIoNZEccT8dIgg/+KJwNcMUwSQCKdwxeFVumWg0vw75hyFWwU6Y9ZiVE8xQLTC2fKFcgFpaBO/SjM2ZJ1U0huvYr1SADna0fSkeiHqfMMKcgnDm2qStVmUeyOs8=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
